apiVersion: apps/v1
kind: Deployment
metadata:
  name: scrapest
spec:
  replicas: 1
  selector:
    matchLabels:
     service: scrapest
  template:
    metadata:
      labels:
        service: scrapest
    spec:
      containers:
      - image: 10596/scrapest
        name: scrapest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "100Mi"
            cpu: "100m"
        env:
        - name: elastic_url
          valueFrom:
            configMapKeyRef:
              name: env-config
              key: elastic_url